id: conceptmaps-ElementsTransverses
canonical: http://example.org/conceptmaps
name: ConceptMapsElementsTransverses
status: draft
version: 1.0.0
fhirVersion: 4.0.1
releaseLabel: STU1
copyrightYear: 2024

# Indique à SUSHI où trouver les fichiers FSH
fshtank:
  - input/fsh

#  Dossier où se trouve le contenu IG
# (nécessaire pour FSH)
include:
  - input