
id: conceptmaps-dataTypes
canonical: http://example.org/conceptmaps
name: ConceptMapsDataTypes
status: draft
version: 1.0.0
fhirVersion: 4.0.1
releaseLabel: STU1
copyrightYear: 2024

FSHOnly: false
FSHDir: input/fsh
